---
- hosts: rhel9.tingnkai.com

  tasks:
    - name: Copy script checkmaster.sh
      ansible.builtin.copy:
        src: checkmaster.sh
        dest: /home/wccheng/checkmaster.sh
        mode: u=rx

    - name: Copy script checkpid.sh
      ansible.builtin.copy:
        src: checkpid.sh
        dest: /home/wccheng/checkpid.sh
        mode: u=rx

    - name: Copy script runbackup.sh
      ansible.builtin.copy:
        src: runbackup.sh
        dest: /home/wccheng/runbackup.sh
        mode: u=rx

    - name: Copy script backupetcd.sh
      ansible.builtin.copy:
        src: backupetcd.sh
        dest: /home/wccheng/backupetcd.sh
        mode: u=rx

    - name: Ensure no backupetcd.sh is runing
      ansible.builtin.command:  /home/wccheng/checkpid.sh

    - name: check master nodes Ready
      ansible.builtin.command:  /home/wccheng/checkmaster.sh
      args:
        stdin: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
      no_log: true

    - name: run backup script
      ansible.builtin.command:  /home/wccheng/runbackup.sh
      args:
        stdin: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
      no_log: false
      when: dry_run != "true"

